ThisBuild / resolvers += Resolver.scalaNightlyRepository
name := "utest"
organization := "com.lihaoyi"
resolvers += "scala-integration" at
  "https://scala-ci.typesafe.com/artifactory/scala-integration/"
scalaVersion := "2.13.17"
libraryDependencies += "org.portable-scala" %% "portable-scala-reflect" % "1.1.3"
libraryDependencies += "org.scala-lang" % "scala-reflect" % scalaVersion.value
libraryDependencies += "org.scala-sbt" % "test-interface" % "1.0"
libraryDependencies += "com.lihaoyi" %% "pprint" % "0.9.3"
libraryDependencies += "com.lihaoyi" %% "fansi" % "0.5.1"
libraryDependencies += "app.tulz" %% "stringdiff" % "0.3.4"
testFrameworks += new TestFramework("test.utest.CustomFramework")
Compile / unmanagedSourceDirectories += baseDirectory.value / "utest" / "src"
Compile / unmanagedSourceDirectories += baseDirectory.value / "utest" / "src-2"
Compile / unmanagedSourceDirectories += baseDirectory.value / "utest" / "src-2.13"
Compile / unmanagedSourceDirectories += baseDirectory.value / "utest" / "src-jvm"
Compile / unmanagedSourceDirectories += baseDirectory.value / "utest" / "src-2-jvm"
Test / unmanagedSourceDirectories += baseDirectory.value / "utest" / "test" / "src"
Test / unmanagedSourceDirectories += baseDirectory.value / "utest" / "test" / "src-jvm"
